#!/bin/sh

BOT_MESSAGE="🤖 Automated formatting and import sorting"

if git log --pretty=%B -n 1 | grep -q $BOT_MESSAGE; then
  echo "No changes to commit."
  exit 0
fi

printf "\e[33;1m%s\e[0m\n" 'Running the Flutter formatter'
dart format .
printf "\e[33;1m%s\e[0m\n" 'Running the import_sorter'
flutter pub run import_sorter:main
printf "\e[33;1m%s\e[0m\n" 'Finished running the import_sorter'

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi

if ! git diff --cached --exit-code > /dev/null; then
  git commit -m $BOT_MESSAGE
  exit 0
fi

exit 0
