// Mocks generated by Mockito 5.4.0 from annotations
// in waterbus/test/features/profile/domain/data/repositories/user_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// Dart imports:
import 'dart:async' as _i3;

// Package imports:
import 'package:mockito/mockito.dart' as _i1;

// Project imports:
import 'package:waterbus/features/auth/data/models/user_model.dart' as _i4;

import 'package:waterbus/features/profile/data/datasources/user_remote_datasource.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i2.UserRemoteDataSource {
  @override
  _i3.Future<_i4.UserModel?> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i3.Future<_i4.UserModel?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.UserModel?>.value(),
      ) as _i3.Future<_i4.UserModel?>);
  @override
  _i3.Future<_i4.UserModel?> updateUserProfile(_i4.UserModel? userModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [userModel],
        ),
        returnValue: _i3.Future<_i4.UserModel?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.UserModel?>.value(),
      ) as _i3.Future<_i4.UserModel?>);
}
