// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCg0POxwRZjYzVd4u571rkyObRdOHC3rvw",
    authDomain: "waterbus-71cf5.firebaseapp.com",
    projectId: "waterbus-71cf5",
    storageBucket: "waterbus-71cf5.appspot.com",
    messagingSenderId: "727554668212",
    appId: "1:727554668212:web:6624269d0494b187b989e1",
    measurementId: "G-3RWKDX1N14",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-yqTO2eRZkIGarZaMK_sAriwr6uVeftc',
    appId: '1:727554668212:android:0253247dd933811eb989e1',
    messagingSenderId: '727554668212',
    projectId: 'waterbus-71cf5',
    storageBucket: 'waterbus-71cf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyZnxK6AZhfHQ-Mn7TE9HFD-h0HyNxcP4',
    appId: '1:727554668212:ios:dcc0bd396135e2ecb989e1',
    messagingSenderId: '727554668212',
    projectId: 'waterbus-71cf5',
    storageBucket: 'waterbus-71cf5.appspot.com',
    androidClientId:
        '727554668212-0sgec37ism3qdfocks8q0k24ruh3gh4d.apps.googleusercontent.com',
    iosClientId:
        '727554668212-b4qpqkcl5792g0gkqng85kugh5c5r51e.apps.googleusercontent.com',
    iosBundleId: 'com.waterbus.wanted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyZnxK6AZhfHQ-Mn7TE9HFD-h0HyNxcP4',
    appId: '1:727554668212:ios:dcc0bd396135e2ecb989e1',
    messagingSenderId: '727554668212',
    projectId: 'waterbus-71cf5',
    storageBucket: 'waterbus-71cf5.appspot.com',
    androidClientId:
        '727554668212-0sgec37ism3qdfocks8q0k24ruh3gh4d.apps.googleusercontent.com',
    iosClientId:
        '727554668212-b4qpqkcl5792g0gkqng85kugh5c5r51e.apps.googleusercontent.com',
    iosBundleId: 'com.waterbus.wanted',
  );
}
