// Mocks generated by Mockito 5.4.4 from annotations
// in waterbus/test/features/profile/data/repositories/user_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// Dart imports:
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

// Package imports:
import 'package:mockito/mockito.dart' as _i1;

// Project imports:
import 'package:waterbus/features/auth/domain/entities/user.dart' as _i4;

import 'package:waterbus/features/profile/data/datasources/user_remote_datasource.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i2.UserRemoteDataSource {
  @override
  _i3.Future<_i4.User?> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i3.Future<_i4.User?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.User?>.value(),
      ) as _i3.Future<_i4.User?>);

  @override
  _i3.Future<bool> updateUserProfile(_i4.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [user],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateUsername(String? username) => (super.noSuchMethod(
        Invocation.method(
          #updateUsername,
          [username],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool?> checkUsername(String? username) => (super.noSuchMethod(
        Invocation.method(
          #checkUsername,
          [username],
        ),
        returnValue: _i3.Future<bool?>.value(),
        returnValueForMissingStub: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<String?> getPresignedUrl() => (super.noSuchMethod(
        Invocation.method(
          #getPresignedUrl,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> uploadImageToS3({
    required String? uploadUrl,
    required _i5.Uint8List? image,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImageToS3,
          [],
          {
            #uploadUrl: uploadUrl,
            #image: image,
          },
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}
