// Mocks generated by Mockito 5.4.0 from annotations
// in waterbus/test/features/auth/data/repositories/auth_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// Dart imports:
import 'dart:async' as _i6;

// Package imports:
import 'package:auth/models/auth_payload_model.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// Project imports:
import 'package:waterbus/features/auth/data/models/token_model.dart' as _i2;
import 'package:waterbus/features/auth/data/models/user_model.dart' as _i4;

import 'package:waterbus/features/auth/data/datasources/auth_local_datasource.dart'
    as _i3;
import 'package:waterbus/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTokenModel_0 extends _i1.SmartFake implements _i2.TokenModel {
  _FakeTokenModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i3.AuthLocalDataSource {
  @override
  void saveUserModel(_i4.UserModel? userModel) => super.noSuchMethod(
        Invocation.method(
          #saveUserModel,
          [userModel],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void saveTokens({
    required String? accessToken,
    required String? refreshToken,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i5.AuthRemoteDataSource {
  @override
  _i6.Future<_i2.TokenModel> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i6.Future<_i2.TokenModel>.value(_FakeTokenModel_0(
          this,
          Invocation.method(
            #refreshToken,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.TokenModel>.value(_FakeTokenModel_0(
          this,
          Invocation.method(
            #refreshToken,
            [],
          ),
        )),
      ) as _i6.Future<_i2.TokenModel>);
  @override
  _i6.Future<_i4.UserModel?> signInWithSocial(
          _i7.AuthPayloadModel? authPayload) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithSocial,
          [authPayload],
        ),
        returnValue: _i6.Future<_i4.UserModel?>.value(),
        returnValueForMissingStub: _i6.Future<_i4.UserModel?>.value(),
      ) as _i6.Future<_i4.UserModel?>);
}
